export const api = {
  async me(){ const r = await fetch('http://localhost:3000/auth/me', { credentials:'include' }); return r.ok ? r.json() : null },
  async login(email:string, password:string){ const r = await fetch('http://localhost:3000/auth/login',{ method:'POST', credentials:'include', headers:{'content-type':'application/json'}, body: JSON.stringify({ email, password })}); if(!r.ok) throw new Error('login'); return r.json() },
  async logout(){ await fetch('http://localhost:3000/auth/logout', { method:'POST', credentials:'include' }) },
  async niveles_list(){ const r=await fetch('http://localhost:3000/niveles',{credentials:'include'}); return r.json() },
  async niveles_create(data:any){ const r=await fetch('http://localhost:3000/niveles',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(data)}); return r.json() },
  async niveles_update(id:string,data:any){ const r=await fetch('http://localhost:3000/niveles/'+id,{method:'PUT',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(data)}); return r.json() },
  async niveles_delete(id:string){ const r=await fetch('http://localhost:3000/niveles/'+id,{method:'DELETE',credentials:'include'}); return r.json() },
  async subniveles_list(){ const r=await fetch('http://localhost:3000/subniveles',{credentials:'include'}); return r.json() },
  async subniveles_create(data:any){ const r=await fetch('http://localhost:3000/subniveles',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(data)}); return r.json() },
  async subniveles_update(id:string,data:any){ const r=await fetch('http://localhost:3000/subniveles/'+id,{method:'PUT',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(data)}); return r.json() },
  async subniveles_delete(id:string){ const r=await fetch('http://localhost:3000/subniveles/'+id,{method:'DELETE',credentials:'include'}); return r.json() },
  async ninos_list(q=''){ const r=await fetch('http://localhost:3000/ninos?q='+encodeURIComponent(q),{credentials:'include'}); return r.json() },
  async ninos_create(data:any){ const r=await fetch('http://localhost:3000/ninos',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(data)}); return r.json() },
  async ninos_update(id:string,data:any){ const r=await fetch('http://localhost:3000/ninos/'+id,{method:'PUT',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(data)}); return r.json() },
  async ninos_delete(id:string){ const r=await fetch('http://localhost:3000/ninos/'+id,{method:'DELETE',credentials:'include'}); return r.json() },
  async usuarios_list(){ const r=await fetch('http://localhost:3000/usuarios',{credentials:'include'}); return r.json() },
  async usuarios_create(data:any){ const r=await fetch('http://localhost:3000/usuarios',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(data)}); return r.json() },
  async usuarios_update(id:string,data:any){ const r=await fetch('http://localhost:3000/usuarios/'+id,{method:'PUT',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(data)}); return r.json() },
  async usuarios_delete(id:string){ const r=await fetch('http://localhost:3000/usuarios/'+id,{method:'DELETE',credentials:'include'}); return r.json() },
}
